name = "herbforagingsim"
uuid = "133e00cd-7c80-4ffa-92ac-1203b18647a7"
authors = ["jdyeakel <jdyeakel@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DataFrames = "1.7.0"
Distributions = "0.25.112"
LinearAlgebra = "1.11.0"
